### ISSUE TITLE
Handle installation of ServiceMonitor CRD

### ISSUE THREAD

**Issue by rollandf** [nmagnezi/observatorium-operator-golang#19]
Is the operator in charge of installing the ServiceMonitor CRD?

kubectl apply -f https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml

**Comment by ErezAlster** [comment]
What is it service monitor?

**Comment by nmagnezi** [comment]
Should we transfer this to https://github.com/observatorium/configuration ?

**Comment by nmagnezi** [comment]
This repo is no longer being maintained.
